name: CI

on:
  push:
    branches:
      - 'main'

env:
  POST: ${{ secrets.POST }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/tobi2k/website:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and pull image
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull ghcr.io/tobi2k/website:latest
            docker stop website
            docker rm website
            rm ./.env && touch ./.env
            echo 'POST=${{ secrets.POST }}' >> ./.env
            docker run -d --restart unless-stopped --network host --name=website --env-file ./.env ghcr.io/tobi2k/website:latest
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
